Add escu test
splunk/addonfactory-repository-template pull request #277
Opened 2022-09-06 11:54 UTC by rajkarkar-crest

2022-09-06 14:53 UTC, bhargav-nariyani-crest approved these changes

2022-09-06 14:55 UTC, uoboda-splunk approved these changes

2022-09-06 15:10 UTC, artemrys approved these changes

2022-09-06 15:10 UTC, artemrys commented on enforce/.github/workflows/escu-manual-workflow.yml
> +name: escu-manual-workflow
Can we add it to the reusable workflow?

2022-09-06 15:10 UTC, artemrys commented on enforce/.github/workflows/escu-manual-workflow.yml
> +          node-version: '14'
I think we don't need this anymore.

2022-09-06 15:10 UTC, artemrys commented on .pre-commit-config.yaml
> +        exclude: ^(tests/requirement_test/logs|tests/knowledge/samples)
Please add `tests/escu/.escu_detections` here as well.

2022-09-06 15:11 UTC, artemrys requested changes

2022-09-06 15:11 UTC, artemrys commented on enforce/.github/workflows/escu-manual-workflow.yml
> +        description: 'Comma-Separated List of detections to run'
What are the expected values here?

2022-09-06 15:49 UTC, rajkarkar-crest commented on enforce/.github/workflows/escu-manual-workflow.yml
> +name: escu-manual-workflow
@artemrys We have already added this test suite to the reusable workflow(https://github.com/splunk/addonfactory-workflow-addon-release/pull/93), but this is a separate workflow that lets the dev team execute this test-suite manually.

2022-09-06 15:57 UTC, rajkarkar-crest commented on enforce/.github/workflows/escu-manual-workflow.yml
> +        description: 'Comma-Separated List of detections to run'
The Dev team has a detection list applicable for the particular add-on. They need to pass the comma-separated list of detection to run. Added example for reference.

2022-09-06 15:58 UTC, rajkarkar-crest commented on .pre-commit-config.yaml
> +        exclude: ^(tests/requirement_test/logs|tests/knowledge/samples)
Added `tests/escu/.escu_detections`.

2022-09-06 15:59 UTC, rajkarkar-crest commented on enforce/.github/workflows/escu-manual-workflow.yml
> +          node-version: '14'
Removing this.

2022-09-06 16:06 UTC, artemrys commented on enforce/.github/workflows/escu-manual-workflow.yml
> +name: escu-manual-workflow
I meant that you can add something like this https://github.com/splunk/addonfactory-workflow-addon-release/blob/main/.github/workflows/reusable-build-test-release.yml, but specifically for the ESCU manual run.

The reason for this is that if we need to change something, we need to push a new change from the template which will trigger a lot of PRs which need to be merged which takes time and unnecessary maintenance.

2022-09-07 09:16 UTC, rajkarkar-crest commented on enforce/.github/workflows/escu-manual-workflow.yml
> +name: escu-manual-workflow
@artemrys Agreed. As per your suggestion, I have added workflow in addonfactory-workflow-addon-release which can be called from addons. I raised a PR https://github.com/splunk/addonfactory-workflow-addon-release/pull/95. Can you please review it?

2022-09-07 12:24 UTC, rajkarkar-crest commented on enforce/.github/workflows/escu-manual-workflow.yml
> +name: escu-manual-workflow
Also updated changes escu-manual-workflow to call workflow from https://github.com/splunk/addonfactory-workflow-addon-release.

2022-09-07 12:34 UTC, uoboda-splunk requested changes

2022-09-07 12:34 UTC, uoboda-splunk commented on enforce/.github/workflows/escu-manual-workflow.yml
> +    uses: splunk/addonfactory-workflow-addon-release/.github/workflows/reusable-escu-manual-workflow.yml@v2.1
It must be a separate repository for `reusable-escu-manual-workflow` We will have a mismatch of versions with `build-test-release` all the time

2022-09-07 12:52 UTC, uoboda-splunk commented on enforce/.github/workflows/escu-manual-workflow.yml
> +    uses: splunk/addonfactory-workflow-addon-release/.github/workflows/reusable-escu-manual-workflow.yml@v2.1
Agreed to do it as follow up task

2022-09-07 12:53 UTC, uoboda-splunk approved these changes

2022-09-07 12:56 UTC, bhargav-nariyani-crest approved these changes

2022-09-07 13:08 UTC, rajkarkar-crest commented on enforce/.github/workflows/escu-manual-workflow.yml
> +    uses: splunk/addonfactory-workflow-addon-release/.github/workflows/reusable-escu-manual-workflow.yml@v2.1
Reference Jira: https://github.com/splunk/addonfactory-repository-template/pull/277

2022-09-07 13:19 UTC, artemrys approved these changes

2022-09-07 13:20 UTC, merged