ci: added individual files for appinspect exception and manual checks
splunk/addonfactory-repository-template pull request #309
Opened 2023-01-03 13:17 UTC by truptilangalia-crest

This PR can only be merged after newer version of addonfactory-workflow-addon-release is released.

2023-01-03 13:54 UTC, uoboda-splunk approved these changes

2023-01-03 13:54 UTC, uoboda-splunk commented on repositories_main.csv
> +splunk-dbx-add-on-for-influxDB,Splunk_JDBC_influxDB,internal,"Splunk DBX Add-on for influxDB JDBC",main
add newline please

2023-01-03 13:57 UTC, uoboda-splunk requested changes

2023-01-03 13:57 UTC, uoboda-splunk commented on tools/sync.sh
> +        mv .app-vetting.yaml .appinspect.manualcheck
What if there are already manual checks and exceptions in `.app-vetting.yaml`?

2023-01-04 10:54 UTC, truptilangalia-crest commented on tools/sync.sh
> +        mv .app-vetting.yaml .appinspect.manualcheck
In that case, .`app-vetting.yaml` will be renamed to `.appinspect.manualcheck.yaml` containing both types of checks. But as failures are not present in `.appinspect.except.yaml` the action will start failing with the message `Some failure checks were found in appinspect output, which are not present in .appinspect.except.yaml` So that the developers can understand that exceptions needs to be presented in `.appinspect.except.yaml` As soon as the developer add the exceptions to appinspect.except.yaml, the action will start passing as previously. The same has been discussed with the dev team as well.

2023-01-04 10:59 UTC, uoboda-splunk commented on tools/sync.sh
> +        mv .app-vetting.yaml .appinspect.manualcheck
Makes sense

2023-01-04 10:59 UTC, uoboda-splunk approved these changes

2023-01-04 10:59 UTC, uoboda-splunk commented
LGTM

2023-01-04 11:15 UTC, kkania-splunk approved these changes

2023-01-04 12:23 UTC, merged